image: docker:24.0
services:
  - docker:24.0-dind

variables:
  DOCKER_BUILDKIT: 1  # Faster builds
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - test
  - scan
  - deploy

# Cache Maven dependencies for faster builds
cache:
  paths:
    - .m2/repository

# Build & push Docker image
build:
  stage: build
  script:
    - docker build -t $DOCKER_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_TAG

# Run tests (skipped in Docker build)
test:
  stage: test
  image: maven:3.8.6-eclipse-temurin-17
  script:
    - mvn test

# Security scans (Trivy for both dependencies & container)
scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy fs --security-checks vuln,config .  # Dependency scan
    - trivy image --exit-code 0 --ignore-unfixed $DOCKER_TAG  # Container scan

# Deploy to a server (example using Docker)
deploy:
  stage: deploy
  only:
    - main
  script:
    - ssh $SERVER_USER@$SERVER_IP "docker pull $DOCKER_TAG && docker run -d -p 8080:8080 $DOCKER_TAG"
