image: docker:24.0

services:
  - name: docker:24.0-dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
    alias: docker
    variables:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://docker:2375

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - scan
  - deploy

before_script:
  - until docker info; do sleep 1; done  # Wait for Docker daemon

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - docker info  # Verify Docker connection
    - docker build -t $DOCKER_TAG .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_TAG
  tags:
    - dockerExec

test:
  stage: test
  image: maven:3.8.6-eclipse-temurin-17
  script:
    - mvn test
  tags:
    - dockerExec

scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy fs --security-checks vuln,config .
    - trivy image --exit-code 0 --ignore-unfixed $DOCKER_TAG
  tags:
    - dockerExec

deploy:
  stage: deploy
  only:
    - main
  script:
    - ssh $SERVER_USER@$SERVER_IP "docker pull $DOCKER_TAG && docker run -d -p 8080:8080 $DOCKER_TAG"
  tags:
    - dockerExec