image: docker:24.0

services:
  - name: docker:24.0-dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
    alias: docker
    variables:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://docker:2375

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=8"
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"
  SAST_DISABLE_DIND: "true"

stages:
  - build
  - test
  - dependency_scan
  - sast
  - container_scan
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
    - target/
  policy: pull-push

build:
  stage: build
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker build --build-arg MAVEN_OPTS="$MAVEN_OPTS" -t $DOCKER_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_TAG
  tags:
    - dockerExec

test:
  stage: test
  needs: ["build"]
  image: maven:3.9.6-eclipse-temurin-17
  variables:
    DOCKER_HOST: ""
    DOCKER_TLS_CERTDIR: ""
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/
  tags:
    - dockerExec

# Include GitLab's SAST template
include:
  - template: Security/SAST.gitlab-ci.yml

dependency_scanning:
  stage: dependency_scan
  needs: ["build"]
  image: owasp/dependency-check:latest
  script:
    - dependency-check.sh --project "$CI_PROJECT_NAME" --scan . --format "ALL" --out "dependency-check-report"
  artifacts:
    when: always
    reports:
      dependency_scanning: dependency-check-report/dependency-check-report.xml
    paths:
      - dependency-check-report/
    expire_in: 1 week
  allow_failure: true
  tags:
    - dockerExec

# Include GitLab's Container Scanning template
include:
  - template: Security/Container-Scanning.gitlab-ci.yml

container_scanning:
  variables:
    DOCKER_IMAGE: $DOCKER_TAG
    CS_DISABLE_DIND: "false"
  needs: ["build"]
  allow_failure: true
  tags:
    - dockerExec

deploy:
  stage: deploy
  needs:
    - job: test
      artifacts: true
    - job: dependency_scanning
    - job: sast
    - job: container_scanning
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - until docker info; do sleep 1; done
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull $DOCKER_TAG
    - docker tag $DOCKER_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker stop spring-app || true
    - docker rm spring-app || true
    - docker run -d --name spring-app -p 8080:8080 $CI_REGISTRY_IMAGE:latest
  only:
    - main
  tags:
    - dockerExec