stages:
  - build
  - test
  - security_scan  # Parallel security scans
  - deploy

variables:
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
    - target/

# Build stage
build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/
  tags:
    - dockerExec

# Test stage
test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn test
  tags:
    - dockerExec

# Security scans (run in parallel)
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

sast:
  stage: security_scan
  variables:
    SAST_EXCLUDED_ANALYZERS: "brakeman,nodejs-scan,eslint,gosec,flawfinder,security-code-scan"
  tags:
    - dockerExec

dependency_scan:
  stage: security_scan
  image: owasp/dependency-check:latest
  script:
    - dependency-check.sh --project "$CI_PROJECT_NAME" --scan . --format "ALL"
  artifacts:
    when: always
    paths:
      - dependency-check-report.html
  allow_failure: true
  tags:
    - dockerExec

container_scan:
  stage: security_scan
  variables:
    CS_IMAGE: $DOCKER_TAG
  tags:
    - dockerExec

# Deployment
deploy:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $DOCKER_TAG .
    - docker push $DOCKER_TAG
    - docker run -d --name myapp -p 8080:8080 $DOCKER_TAG
  only:
    - main
  tags:
    - dockerExec