image: docker:24.0

services:
  - name: docker:24.0-dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
    alias: docker
    variables:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://docker:2375

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=8"
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"

stages:
  - build
  - test
  - security
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
    - target/
  policy: pull-push

build:
  stage: build
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker build --build-arg MAVEN_OPTS="$MAVEN_OPTS" -t $DOCKER_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_TAG
  tags:
    - dockerExec

test:
  stage: test
  needs: ["build"]
  image: maven:3.9.6-eclipse-temurin-17
  variables:
    DOCKER_HOST: ""
    DOCKER_TLS_CERTDIR: ""
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/
  tags:
    - dockerExec

# Include all security scanning templates
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

# Configure security jobs
sast:
  stage: security
  needs: ["build"]
  variables:
    SAST_EXCLUDED_ANALYZERS: "brakeman,nodejs-scan,eslint,gosec,flawfinder,security-code-scan"
  tags:
    - dockerExec

dependency_scanning:
  stage: security
  needs: ["build"]
  tags:
    - dockerExec

container_scanning:
  stage: security
  variables:
    DOCKER_IMAGE: $DOCKER_TAG
  needs: ["build"]
  tags:
    - dockerExec

deploy:
  stage: deploy
  needs:
    - job: test
      artifacts: true
    - job: sast
    - job: dependency_scanning
    - job: container_scanning
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - until docker info; do sleep 1; done
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull $DOCKER_TAG
    - docker tag $DOCKER_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker stop spring-app || true
    - docker rm spring-app || true
    - docker run -d --name spring-app -p 8080:8080 $CI_REGISTRY_IMAGE:latest
  only:
    - main
  tags:
    - dockerExec