image: docker:24.0

services:
  - name: docker:24.0-dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
    alias: docker
    variables:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://docker:2375

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"

stages:
  - build
  - test
  - sast
  - dependency_scan
  - container_scan
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
    - target/
  policy: pull-push

build_job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/
    reports:
      junit: target/surefire-reports/*.xml
  tags:
    - dockerExec

test_job:
  stage: test
  needs: ["build_job"]
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn test $MAVEN_CLI_OPTS
  tags:
    - dockerExec

# Security Scanning Templates
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

# SAST Configuration
sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: "brakeman,nodejs-scan,eslint,gosec,flawfinder,security-code-scan"
  needs: ["build_job"]
  tags:
    - dockerExec

# Dependency Scanning
dependency_scanning:
  stage: dependency_scan
  needs: ["build_job"]
  image: owasp/dependency-check:latest
  script:
    - dependency-check.sh --project "$CI_PROJECT_NAME" --scan . --format "ALL" --out "dependency-check-report"
  artifacts:
    when: always
    reports:
      dependency_scanning: dependency-check-report/dependency-check-report.xml
    paths:
      - dependency-check-report/
    expire_in: 1 week
  allow_failure: true
  tags:
    - dockerExec

# Container Scanning Configuration
container_scanning:
  variables:
    DOCKER_IMAGE: $DOCKER_TAG
  needs: ["build_job"]
  allow_failure: true
  tags:
    - dockerExec

# Deployment
deploy:
  stage: deploy
  needs:
    - job: test_job
    - job: sast
    - job: dependency_scanning
    - job: container_scanning
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - until docker info; do sleep 1; done
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $DOCKER_TAG .
    - docker tag $DOCKER_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker stop spring-app || true
    - docker rm spring-app || true
    - docker run -d --name spring-app -p 8080:8080 $CI_REGISTRY_IMAGE:latest
  only:
    - main
  tags:
    - dockerExec