stages:
  - build
  - package
  - test
  - security_scan
  - deploy

variables:
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
    - target/

# Stage 1: Build Java application
maven_build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/
  tags:
    - dockerExec

# Stage 2: Build and push Docker image
docker_build:
  stage: package
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_TAG .
    - docker push $DOCKER_TAG
  needs: ["maven_build"]
  tags:
    - dockerExec

# Stage 3: Run tests
test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn test
  needs: ["maven_build"]
  tags:
    - dockerExec

# Security scans (run in parallel)
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

sast:
  stage: security_scan
  variables:
    SAST_EXCLUDED_ANALYZERS: "brakeman,nodejs-scan,eslint,gosec,flawfinder,security-code-scan"
  needs: ["maven_build"]
  tags:
    - dockerExec

container_scanning:
  stage: security_scan
  variables:
    CS_IMAGE: $DOCKER_TAG
  needs: ["docker_build"]
  tags:
    - dockerExec

# Deployment
deploy:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $DOCKER_TAG
    - docker tag $DOCKER_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker stop myapp || true
    - docker rm myapp || true
    - docker run -d --name myapp -p 8080:8080 $CI_REGISTRY_IMAGE:latest
  only:
    - main
  needs: ["test", "sast", "container_scanning"]
  tags:
    - dockerExec