image: docker:24.0

services:
  - name: docker:24.0-dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
    alias: docker
    variables:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://docker:2375

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  TRIVY_NO_PROGRESS: "true"

stages:
  - build
  - test
  - scan
  - deploy

cache:
  paths:
    - .m2/repository
    - target/

build:
  stage: build
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker build -t $DOCKER_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_TAG
  tags:
    - dockerExec

test:
  stage: test
  image: maven:3.8.6-eclipse-temurin-17
  variables:
    DOCKER_HOST: ""
    DOCKER_TLS_CERTDIR: ""
  script:
    - mvn --batch-mode test
  cache:
    paths:
      - .m2/repository
      - target/
  tags:
    - dockerExec

scan:
  stage: scan
  image: docker:24.0
  before_script:
    # Install Trivy using the official installation method
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.tar.gz
    - tar -xzf trivy_0.49.1_Linux-64bit.tar.gz
    - mv trivy /usr/local/bin/
    - until docker info; do sleep 1; done
  script:
    # Filesystem scan
    - trivy fs --security-checks vuln,config .
    # Image scan (using the local image)
    - trivy image --exit-code 0 --ignore-unfixed $DOCKER_TAG
  dependencies:
    - build
  tags:
    - dockerExec

deploy:
  stage: deploy
  only:
    - main
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY && docker pull $DOCKER_TAG && docker stop spring-app || true && docker rm spring-app || true && docker run -d --name spring-app -p 8080:8080 $DOCKER_TAG"
  tags:
    - dockerExec